spring:
  application:
    name: mihneapopa
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/simplilearn
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.type: INFO
    org.springframework: DEBUG
